name = "nDent"
uuid = "afe7e263-2d72-4c41-8b5a-102fbb6459a8"
authors = ["Helena Cala <116077244+helenacala@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
